// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrzepisyDlaCiebie.Models;

namespace PrzepisyDlaCiebie.Migrations
{
    [DbContext(typeof(PrzepisDbContext))]
    [Migration("20210616225334_AddPrzepisyToDb")]
    partial class AddPrzepisyToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrzepisyDlaCiebie.Models.Przepis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaPrzepisu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NazwaZdjecia")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TrescPrzepisu")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("przepisy");
                });
#pragma warning restore 612, 618
        }
    }
}
